import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import ModalChat from "@/components/ModalChat";
import Transcriptor from "@/components/Transcriptor";
import { Toaster } from "react-hot-toast";

const figtreeFont = localFont({
  src: "./fonts/Figtree.ttf",
  variable: "--font-figtree-sans",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtreeFont.variable} antialiased min-h-screen bg-green-100`}
      >
        <div className="h-full">
          <ModalChat />
          <Toaster />
          <Transcriptor />
          <nav className="bg-green-600">
            <div className="p-4 max-w-7xl m-auto">
              <div className="flex items-center justify-between gap-2">
                <h1 className="text-white text-4xl font-bold">
                  Asistente virtual - UTS
                </h1>
                <Image
                  src={"/images/uts.png"}
                  alt="Unidades tecnológicas de santander"
                  width={100}
                  height={100}
                  className="rounded-md"
                />
              </div>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
